# Generated by Django 5.2.4 on 2025-07-07 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('Device_id', models.CharField(primary_key=True, serialize=False)),
                ('User_name', models.CharField(max_length=30)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
                ('Mob', models.BigIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_message', models.CharField(max_length=100)),
                ('Time_stamp', models.CharField(max_length=100)),
                ('Device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.myuser')),
            ],
        ),
    ]
