# Generated by Django 5.2.4 on 2025-07-08 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_myuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='reset_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
