# Generated by Django 5.2.4 on 2025-07-08 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_myuser_reset_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='reset_token',
        ),
    ]
